from django.db import models


PRODUCT_NAME_MAX_LENGTH: int = 25
PRODUCT_CATEGORY_MAX_LENGTH: int = 20


class ProductCategory(models.TextChoices):
    LAPTOP = 'Laptop', 'Laptop'
    SMARTPHONE = 'Smartphone', 'Smartphone'
    TV = 'TV', 'TV'
    TABLET = 'Tablet', 'Tablet'
    COMPUTER = 'Computer', 'Computer'
    HEADSET = 'Headset', 'Headset'
    MONITOR = 'Monitor', 'Monitor'


PRODUCT_PRICE_MAX_DIGITS: int = 10
PRODUCT_PRICE_DECIMAL_PLACES: int = 2
PRODUCT_PRICE_MIN_VALUE: int = 1
PRODUCT_DISCOUNT_PERCENTAGE_DEFAULT_VALUE: int = 0
PRODUCT_DISCOUNT_PERCENTAGE_MIN_VALUE: int = 0
PRODUCT_DISCOUNT_PERCENTAGE_MAX_VALUE: int = 100
PRODUCT_IMAGE_UPLOAD_DIRECTORY: str = 'products/'

CART_SUBTOTAL_MAX_DIGITS: int = 10
CART_SUBTOTAL_DECIMAL_PLACES: int = 2
CART_SUBTOTAL_DEFAULT_VALUE: int = 0

ORDER_USER_RELATED_NAME: str = 'orders'
ORDER_PRICE_MAX_DIGITS: int = 10
ORDER_PRICE_DECIMAL_PLACES: int = 2

CARTITEM_CART_RELATED_NAME: str = 'cartitems'
CARTITEM_QUANTITY_MIN_VALUE: int = 1
CARTITEM_QUANTITY_MAX_VALUE: int = 25

SERIALIZER_MAX_DIGITS: int = 10
SERIALIZER_DECIMAL_PLACES: int = 2
