# Generated by Django 5.0.7 on 2024-07-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_count',
            new_name='items_count',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='regular_price',
        ),
    ]
