# Generated by Django 5.0.7 on 2024-07-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_price_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('TV', 'TV'), ('Tablet', 'Tablet'), ('Computer', 'Computer'), ('Headset', 'Headset'), ('Monitor', 'Monitor')], max_length=20),
        ),
    ]
