// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260102201712_Iniotial2")]
    partial class Iniotial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Street", "Backend.Domain.Entities.Address.Street#Street", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Number")
                                .HasColumnType("int")
                                .HasColumnName("StreetNumber");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("StreetName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyIsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Currencies", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.DiscountCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("DiscountCoupons", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Exchange", b =>
                {
                    b.Property<int>("FromCurrencyId")
                        .HasColumnType("int");

                    b.Property<int>("ToCurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FromCurrencyId", "ToCurrencyId");

                    b.HasIndex("ToCurrencyId");

                    b.ToTable("Exchanges", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountCouponId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProductBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitialPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelName")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("nvarchar(125)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTokenType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Suggestions", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SuggestedProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "SuggestedProductId");

                    b.HasIndex("SuggestedProductId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("Wishlist", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("Backend.Domain.Entities.GraphicsCard", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("BusWidth")
                        .HasColumnType("int");

                    b.Property<int>("CudaCores")
                        .HasColumnType("int");

                    b.Property<int>("DirectXSupport")
                        .HasColumnType("int");

                    b.Property<int>("Tdp")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("ClockSpeed", "Backend.Domain.Entities.GraphicsCard.ClockSpeed#ClockSpeed", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Base")
                                .HasColumnType("float")
                                .HasColumnName("ClockSpeedBase");

                            b1.Property<double>("Boost")
                                .HasColumnType("float")
                                .HasColumnName("ClockSpeedBoost");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Memory", "Backend.Domain.Entities.GraphicsCard.Memory#Memory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CapacityInGb")
                                .HasColumnType("int")
                                .HasColumnName("MemoryCapacity");

                            b1.Property<int>("Frequency")
                                .HasColumnType("int")
                                .HasColumnName("MemoryFrequency");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("MemoryType");
                        });

                    b.ToTable("GraphicsCards", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Monitor", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("Brightness")
                        .HasColumnType("int");

                    b.Property<int>("ColorSpectre")
                        .HasColumnType("int");

                    b.Property<double>("DisplayDiagonal")
                        .HasColumnType("float");

                    b.Property<double>("Latency")
                        .HasColumnType("float");

                    b.Property<int>("Matrix")
                        .HasColumnType("int");

                    b.Property<double>("PixelSize")
                        .HasColumnType("float");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("Resolution", "Backend.Domain.Entities.Monitor.Resolution#Resolution", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("int")
                                .HasColumnName("ResolutionHeight");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("ResolutionType");

                            b1.Property<int>("Width")
                                .HasColumnType("int")
                                .HasColumnName("ResolutionWidth");
                        });

                    b.ToTable("Monitors", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Motherboard", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("Chipset")
                        .HasColumnType("int");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<int>("PcieSlots")
                        .HasColumnType("int");

                    b.Property<int>("RamSlots")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.PowerSupply", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("EfficiencyPercentage")
                        .HasColumnType("int");

                    b.Property<int>("FormFactor")
                        .HasColumnType("int");

                    b.Property<int>("Modularity")
                        .HasColumnType("int");

                    b.Property<int>("Wattage")
                        .HasColumnType("int");

                    b.ToTable("PowerSupplies", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Processor", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.Property<int>("Tdp")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("ClockSpeed", "Backend.Domain.Entities.Processor.ClockSpeed#ClockSpeed", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Base")
                                .HasColumnType("float")
                                .HasColumnName("ClockSpeedBase");

                            b1.Property<double>("Boost")
                                .HasColumnType("float")
                                .HasColumnName("ClockSpeedBoost");
                        });

                    b.ToTable("Processors", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ram", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ComplexProperty<Dictionary<string, object>>("Memory", "Backend.Domain.Entities.Ram.Memory#Memory", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CapacityInGb")
                                .HasColumnType("int")
                                .HasColumnName("MemoryCapacity");

                            b1.Property<int>("Frequency")
                                .HasColumnType("int")
                                .HasColumnName("MemoryFrequency");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("MemoryType");
                        });

                    b.ToTable("RAMs", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ssd", b =>
                {
                    b.HasBaseType("Backend.Domain.Entities.ProductBase");

                    b.Property<int>("CapacityInGb")
                        .HasColumnType("int");

                    b.Property<int>("StorageInterface")
                        .HasColumnType("int");

                    b.ComplexProperty<Dictionary<string, object>>("OperationSpeed", "Backend.Domain.Entities.Ssd.OperationSpeed#OperationSpeed", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Read")
                                .HasColumnType("int")
                                .HasColumnName("ReadSpeed");

                            b1.Property<int>("Write")
                                .HasColumnType("int")
                                .HasColumnName("WriteSpeed");
                        });

                    b.ToTable("SSDs", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entities.Address", b =>
                {
                    b.HasOne("Backend.Domain.Entities.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("Backend.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.City", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Backend.Domain.Entities.DiscountCoupon", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Order", "Order")
                        .WithOne("DiscountCoupon")
                        .HasForeignKey("Backend.Domain.Entities.DiscountCoupon", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Exchange", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Currency", "FromCurrency")
                        .WithMany()
                        .HasForeignKey("FromCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.Currency", "ToCurrency")
                        .WithMany()
                        .HasForeignKey("ToCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromCurrency");

                    b.Navigation("ToCurrency");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Item", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Domain.Entities.ProductBase", "Product")
                        .WithMany("Items")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Order", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Shipment", "Shipment")
                        .WithMany("Orders")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Backend.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProductBase", b =>
                {
                    b.HasOne("Backend.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Review", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Sale", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Domain.Entities.UserToken", b =>
                {
                    b.HasOne("Backend.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Suggestions", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithMany()
                        .HasForeignKey("SuggestedProductId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wishlist", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.GraphicsCard", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.GraphicsCard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Monitor", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.Monitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Motherboard", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.Motherboard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.PowerSupply", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.PowerSupply", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Processor", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.Processor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ram", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.Ram", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Ssd", b =>
                {
                    b.HasOne("Backend.Domain.Entities.ProductBase", null)
                        .WithOne()
                        .HasForeignKey("Backend.Domain.Entities.Ssd", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Backend.Domain.Entities.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Order", b =>
                {
                    b.Navigation("DiscountCoupon")
                        .IsRequired();

                    b.Navigation("Items");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Backend.Domain.Entities.ProductBase", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reviews");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Backend.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
